// CommandIndex.ts - Module for my commands index.
// Mar 24, 2021
// Chris M.
// https://github.com/RealTimeChris
'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var botCommands = new Map();
var addshopitem_1 = __importDefault(require("./commands/addshopitem"));
botCommands.set(addshopitem_1.default.name, addshopitem_1.default);
var addshoprole_1 = __importDefault(require("./commands/addshoprole"));
botCommands.set(addshoprole_1.default.name, addshoprole_1.default);
var balance_1 = __importDefault(require("./commands/balance"));
botCommands.set(balance_1.default.name, balance_1.default);
var blackjack_1 = __importDefault(require("./commands/blackjack"));
botCommands.set(blackjack_1.default.name, blackjack_1.default);
var botinfo_1 = __importDefault(require("./commands/botinfo"));
botCommands.set(botinfo_1.default.name, botinfo_1.default);
var buy_1 = __importDefault(require("./commands/buy"));
botCommands.set(buy_1.default.name, buy_1.default);
var casinostats_1 = __importDefault(require("./commands/casinostats"));
botCommands.set(casinostats_1.default.name, casinostats_1.default);
var coinflip_1 = __importDefault(require("./commands/coinflip"));
botCommands.set(coinflip_1.default.name, coinflip_1.default);
var deletedbentry_1 = __importDefault(require("./commands/deletedbentry"));
botCommands.set(deletedbentry_1.default.name, deletedbentry_1.default);
var deposit_1 = __importDefault(require("./commands/deposit"));
botCommands.set(deposit_1.default.name, deposit_1.default);
var displayguildsdata_1 = __importDefault(require("./commands/displayguildsdata"));
botCommands.set(displayguildsdata_1.default.name, displayguildsdata_1.default);
var duel_1 = __importDefault(require("./commands/duel"));
botCommands.set(duel_1.default.name, duel_1.default);
var gamehouseoptions_1 = __importDefault(require("./commands/gamehouseoptions"));
botCommands.set(gamehouseoptions_1.default.name, gamehouseoptions_1.default);
var help_1 = __importDefault(require("./commands/help"));
botCommands.set(help_1.default.name, help_1.default);
var inventory_1 = __importDefault(require("./commands/inventory"));
botCommands.set(inventory_1.default.name, inventory_1.default);
var leaderboard_1 = __importDefault(require("./commands/leaderboard"));
botCommands.set(leaderboard_1.default.name, leaderboard_1.default);
var listdbguilds_1 = __importDefault(require("./commands/listdbguilds"));
botCommands.set(listdbguilds_1.default.name, listdbguilds_1.default);
var message_1 = __importDefault(require("./commands/message"));
botCommands.set(message_1.default.name, message_1.default);
var removeobject_1 = __importDefault(require("./commands/removeobject"));
botCommands.set(removeobject_1.default.name, removeobject_1.default);
var removeshopitem_1 = __importDefault(require("./commands/removeshopitem"));
botCommands.set(removeshopitem_1.default.name, removeshopitem_1.default);
var removeshoprole_1 = __importDefault(require("./commands/removeshoprole"));
botCommands.set(removeshoprole_1.default.name, removeshoprole_1.default);
var rob_1 = __importDefault(require("./commands/rob"));
botCommands.set(rob_1.default.name, rob_1.default);
var roulette_1 = __importDefault(require("./commands/roulette"));
botCommands.set(roulette_1.default.name, roulette_1.default);
var selldrugs_1 = __importDefault(require("./commands/selldrugs"));
botCommands.set(selldrugs_1.default.name, selldrugs_1.default);
var setbalance_1 = __importDefault(require("./commands/setbalance"));
botCommands.set(setbalance_1.default.name, setbalance_1.default);
var setbordercolor_1 = __importDefault(require("./commands/setbordercolor"));
botCommands.set(setbordercolor_1.default.name, setbordercolor_1.default);
var setgamechannel_1 = __importDefault(require("./commands/setgamechannel"));
botCommands.set(setgamechannel_1.default.name, setgamechannel_1.default);
var shop_1 = __importDefault(require("./commands/shop"));
botCommands.set(shop_1.default.name, shop_1.default);
var slashcommands_1 = __importDefault(require("./commands/slashcommands"));
botCommands.set(slashcommands_1.default.name, slashcommands_1.default);
var slots_1 = __importDefault(require("./commands/slots"));
botCommands.set(slots_1.default.name, slots_1.default);
var test_1 = __importDefault(require("./commands/test"));
botCommands.set(test_1.default.name, test_1.default);
var transfer_1 = __importDefault(require("./commands/transfer"));
botCommands.set(transfer_1.default.name, transfer_1.default);
var withdraw_1 = __importDefault(require("./commands/withdraw"));
botCommands.set(withdraw_1.default.name, withdraw_1.default);
exports.default = botCommands;
